// <auto-generated />
using Cyberpolygon.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Cyberpolygon.Migrations
{
    [DbContext(typeof(ConfigurationContext))]
    [Migration("20230625200121_AddBats")]
    partial class AddBats
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Cyberpolygon.Models.Configuration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("AdminPassword")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AdminUsername")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AutounattendPath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CoresNumber")
                        .HasColumnType("int");

                    b.Property<int>("DiskSizeNumber")
                        .HasColumnType("int");

                    b.Property<string>("IsoFilename")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OS")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RamNumber")
                        .HasColumnType("int");

                    b.Property<string>("VmTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("cobian")
                        .HasColumnType("bit");

                    b.Property<bool>("folder")
                        .HasColumnType("bit");

                    b.Property<bool>("ftp")
                        .HasColumnType("bit");

                    b.Property<bool>("hotfix7")
                        .HasColumnType("bit");

                    b.Property<bool>("hotfix812")
                        .HasColumnType("bit");

                    b.Property<bool>("pass")
                        .HasColumnType("bit");

                    b.Property<bool>("port3389")
                        .HasColumnType("bit");

                    b.Property<bool>("port445")
                        .HasColumnType("bit");

                    b.Property<bool>("port80")
                        .HasColumnType("bit");

                    b.Property<bool>("ports3389445")
                        .HasColumnType("bit");

                    b.Property<bool>("ports3389445443")
                        .HasColumnType("bit");

                    b.Property<bool>("ports804438080")
                        .HasColumnType("bit");

                    b.Property<bool>("postgresql")
                        .HasColumnType("bit");

                    b.Property<bool>("powershell")
                        .HasColumnType("bit");

                    b.Property<bool>("prox")
                        .HasColumnType("bit");

                    b.Property<bool>("veeam")
                        .HasColumnType("bit");

                    b.Property<bool>("zip")
                        .HasColumnType("bit");

                    b.Property<bool>("zipmsi")
                        .HasColumnType("bit");

                    b.Property<bool>("ziptest")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Configuration");
                });
#pragma warning restore 612, 618
        }
    }
}
